# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build base and dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Create working directory
WORKDIR /app

# Copy the source code
COPY . /app

# Install pip dependencies without running scripts
RUN pip install --upgrade pip \
    && pip install --ignore-installed --no-cache-dir --prefer-binary .

# Expose port 9030 (default) - might be overridden by config
EXPOSE 9030

# Set entrypoint to run the MCP server
ENTRYPOINT ["python", "-m", "mcp_server_starrocks"]
